---
title: "Data processing"
output: html_notebook
---

Ctrl + Shift + Enter - run cell.
Ctrl + Alt + I - insert new cell.
Ctrl + Shift + K - preview HTML result document.

```{r}
catn <- function(x, append="\n"){cat(x); cat(append)}
```


# Download data

```{r}
file_path = './Data/OnlineNewsPopularity_processed.csv'
data = read.csv(file_path)
print(dim(data))
head(data)
```


```{r}
data = data[, -1] # removing url column
head(data)
```


# Subsetting training data

```{r}
train_percent = 0.1

sample <- sample.int(
  n = nrow(data), 
  size = floor(train_percent*nrow(data)), 
  replace = F
)

train <- data[sample, ]
test  <- data[-sample, ]

cat('Train size', dim(train), '\n')
cat('Test size', dim(test), '\n')
```



# Simple linear model


```{r}
Y_colname = colnames(data)[length(colnames(data))]
X_colnames = colnames(data)[1 : length(colnames(data)) - 1]

X = as.matrix(data[, X_colnames])
Y = data[, Y_colname]

stopifnot(length(Y_colname) + length(X_colnames) == dim(data)[2])
```

```{r}
length(X_colnames)
```


## Full linear model

```{r}
full_model = lm(train[,Y_colname] ~ ., data = train[, 1 : dim(train)[2] - 1])
```


### Model summary
```{r}
summary(full_model)
```
```{r}
par(mfrow = c(2, 2))
plot(full_model)
par(mfrow = c(1, 1))
```


### Model residuals plot

```{r}
colnames(train)
```
```{r}
plot_residuals <- function(model){
  plot(
    fitted(model),
    residuals(model),
    col = 'gray40',
    xlab = 'fitted values',
    ylab = 'residuals'
  )
  
  lines(
    loess.smooth(fitted(model), residuals(model)),
    col = "blue",
    lwd = 4
  )
  abline(h = 0, lty = 3)
}

par(mfrow = c(1, 2))
plot(train$timedelta, train$shares)
abline(full_model, col = "blue", lwd = 20)
plot_residuals(full_model)
par(mfrow = c(1, 1))
```


```{r}
plot(data$shares, data$n_tokens_content, pch = 5)
abline(full_model)
```




```{r}
# To look at coefficients
# coefficients(full_model)

# Confidence intervals for coefficients
# confint(full_model)

# Residuals
# e = residuals(full_model)

# summary(model)
# anova(full_model, reduced_model)  # Script #2 - F-test for comparison of models

# Update model
# red.mod <- update(full.mod, ~.-weight)
# summary(red.mod)
```

```{r}
e <- residuals(full_model)
RSS <- sum(e^2)
RSS
```

```{r}
plot(train$n_tokens_content, residuals(train))
plot(train$average_token_length, residuals(train))
```








## Full linear model (Y log transform)

```{r}
full_model_log = lm(log(train[,Y_colname]) ~ ., data = train[, 1 : dim(train)[2] - 1])
```

## Model summary

```{r}
summary(full_model_log)
```


```{r}
par(mfrow = c(2, 2))
plot(full_model_log)
par(mfrow = c(1, 1))
```

```{r}
plot_residuals(full_model_log)
```


